# Generated by Django 4.1.1 on 2022-09-27 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('actores', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
            ],
        ),
        migrations.CreateModel(
            name='Rentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renta', models.DateTimeField(verbose_name='Fecha de la Renta')),
                ('pelicula_rentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentaPeliculas.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rentas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentaPeliculas.rentas')),
            ],
        ),
    ]
