# Generated by Django 4.1.1 on 2022-09-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentaPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentas',
            name='pelicula_rentada',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rentas',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Rentas',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
