# Generated by Django 4.1.1 on 2022-09-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentaPeliculas', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentas',
            name='pelicula_rentada',
        ),
        migrations.RemoveField(
            model_name='rentas',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Rentas',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
