# Generated by Django 4.1.1 on 2022-09-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentaPeliculas', '0008_alter_pelicula_director_alter_usuario_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentas',
            name='pelicula_rentada',
        ),
        migrations.RemoveField(
            model_name='rentas',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Rentas',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
