# Generated by Django 4.1.1 on 2022-09-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentaPeliculas', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renta',
            name='pelicula_rentada',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Renta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
