# Generated by Django 4.0.6 on 2022-09-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RentaPeliculas', '0011_remove_renta_pelicula_rentada_remove_renta_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('duracion', models.TimeField(verbose_name='Duración')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RentaPeliculas.categoria')),
                ('genero', models.ManyToManyField(to='RentaPeliculas.genero')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'ordering': ['fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_renta', models.DateTimeField(verbose_name='Fecha de la Renta')),
                ('pelicula_rentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentaPeliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentaPeliculas.usuario')),
            ],
            options={
                'verbose_name': 'Renta',
                'verbose_name_plural': 'Rentas',
                'ordering': ['id'],
            },
        ),
    ]
