# Generated by Django 4.0.6 on 2022-09-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentaPeliculas', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='pelicula_rentada',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Renta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
