# Generated by Django 4.0.6 on 2022-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentaPeliculas', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.ManyToManyField(to='RentaPeliculas.director'),
        ),
    ]
