# Generated by Django 4.0.6 on 2022-09-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentaPeliculas', '0015_remove_pelicula_director_pelicula_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='personajes_principales',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='personajes_principales',
            field=models.ManyToManyField(to='RentaPeliculas.personaje'),
        ),
    ]
