# Generated by Django 4.0.6 on 2022-10-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentaPeliculas', '0016_remove_pelicula_personajes_principales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categoria',
            field=models.ManyToManyField(to='RentaPeliculas.categoria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
